name: Deploy rails-dev website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          echo "${{secrets.SSH_PUBLIC_KEY}}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            cd /home/ubuntu/website/rails-dev

            git rebase --abort
            git reset --hard origin/main
            git checkout main

            echo "Pulling latest code..."
            git pull --rebase --prune

            echo "Installing dependencies..."
            npm install

            echo "Building project..."
            npm run build

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
